# Generated by Django 4.2.1 on 2023-05-15 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freeP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages', models.CharField(max_length=100)),
                ('Reserve_Points', models.IntegerField()),
                ('Day1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day2', to='freeP.days')),
                ('Day2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day3', to='freeP.days')),
                ('Day3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day4', to='freeP.days')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('Free', models.BooleanField()),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day5', to='freeP.days')),
                ('Free_Period_Taken_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day6', to=settings.AUTH_USER_MODEL)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
