# Generated by Django 4.2.1 on 2023-05-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeP', '0002_days_details_period_delete_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Messages',
            field=models.TextField(max_length=100),
        ),
    ]
